Repository ms-club-sliit/msclubwesite-v2, pull requests merged in 2021-12, with the labels that each got.

#30 Integrate ContactUs with Backend
  .env
  package.json
  src/api/ContactAction.ts
  src/constants/index.ts
  src/data/BoardSectionData.json
  src/pages/contact/contact-form-section.tsx
  yarn.lock
Labels: feature

#28 Feature/application form UI
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  public/assets/join_us_header.svg
  src/App.scss
  src/interfaces/ContactFormInterface.ts
  src/interfaces/JoinUsFormInterface.ts
  src/pages/contact/contact-form-section.tsx
  src/pages/home/hero-section.tsx
  src/pages/index.ts
  src/pages/join_us/hero-section.tsx
  src/pages/join_us/index.tsx
  src/pages/join_us/join-us-form-section.tsx
  src/routes/app-routes.tsx
  yarn.lock
Labels: validation, high-priority, feature

#32 Application form integrated with backend closes #31
  package-lock.json
  src/api/ApplicationAction.ts
  src/constants/index.ts
  src/pages/join_us/join-us-form-section.tsx
  yarn.lock
Labels: high-priority, feature

#34 Development
  .env
  .github/templates/ISSUE_TEMPLATE.md
  .github/templates/PR_TEMPLATE.md
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  public/assets/join_us_header.svg
  src/App.scss
  src/api/ApplicationAction.ts
  src/api/ContactAction.ts
  src/constants/index.ts
  src/data/BoardSectionData.json
  src/interfaces/ContactFormInterface.ts
  src/interfaces/JoinUsFormInterface.ts
  src/pages/contact/contact-form-section.tsx
  src/pages/home/hero-section.tsx
  src/pages/index.ts
  src/pages/join_us/hero-section.tsx
  src/pages/join_us/index.tsx
  src/pages/join_us/join-us-form-section.tsx
  src/routes/app-routes.tsx
  yarn.lock
Labels: high-priority

#36 Feature/3D logo
  package.json
  public/assets/logo.gltf
  src/components/index.ts
  src/components/logo-3d-model/index.tsx
  src/pages/home/hero-section.tsx
  src/styles/home.scss
  yarn.lock
Labels: high-priority, feature

#38 Fix/bugs
  public/assets/mlsa_logo.png
  public/assets/ms_club_logo_light.png
  src/components/footer/index.tsx
  src/pages/home/blogs-section.tsx
  src/styles/home.scss
Labels: fix

#39 Fixed footer logo size and gap
  src/components/footer/index.tsx
Labels: fix

#41 Boardmember details added
  public/assets/boards/2021/Dilmi.jpeg
  public/assets/boards/2021/Hansidu.jpeg
  public/assets/boards/2021/Lahiru.jpg
  public/assets/boards/2021/Lasal.jpg
  public/assets/boards/2021/Miyuru.jpeg
  public/assets/boards/2021/Nisal.jpg
  public/assets/boards/2021/Rusiru.jpeg
  public/assets/boards/2021/Senura.jpg
  public/assets/boards/2021/Susith.jpg
  public/assets/boards/2021/Yasiru.jpg
  src/data/BoardSectionData.json
  src/pages/board/board-by-year.tsx
Labels: high-priority

#40 Added storyset for only mobile device in the hero section
  src/pages/home/hero-section.tsx
  src/styles/home.scss
Labels: fix

#48 Fixed UI bug in board member section
  src/pages/board/board-by-year.tsx
  src/styles/board.scss
Labels: bug

#50 Changes in Board Member Section
  src/data/BoardSectionData.json
  src/interfaces/BoardInterface.ts
  src/pages/about/hero-section.tsx
  src/pages/board/board-member-card.tsx
  src/pages/home/hero-section.tsx
Labels: bug

#52 Fix board members social medial links issue
  src/data/BoardSectionData.json
  src/interfaces/BoardInterface.ts
Labels: bug, high-priority, fix

#53 Development
  src/data/BoardSectionData.json
  src/interfaces/BoardInterface.ts
Labels: bug, high-priority, fix

#58 Hard coded data added to translation.json
  package-lock.json
  src/components/card/index.tsx
  src/components/footer/index.tsx
  src/components/nav_bar/index.tsx
  src/locales/en-US/translation.json
  src/pages/about/hero-section.tsx
  src/pages/about/pioneers-section.tsx
  src/pages/blog/blog-list-section.tsx
  src/pages/blog/hero-section.tsx
  src/pages/board/board-by-year.tsx
  src/pages/contact/contact-form-section.tsx
  src/pages/contact/hero-section.tsx
  src/pages/event/hero-section.tsx
  src/pages/event/past-events.tsx
  src/pages/event/past-webina.tsx
  src/pages/event/top-speakers.tsx
  src/pages/home/blogs-section.tsx
  src/pages/home/past-events-section.tsx
  src/pages/home/past-webinars-section.tsx
  src/pages/home/who-we-are-section.tsx
  src/pages/join_us/hero-section.tsx
  src/pages/join_us/join-us-form-section.tsx
Labels: feature
