Repository ms-club-sliit/msclubwesite-v2, pull requests merged in 2021-11, with the labels that each got.

#17 Feat(contact us):create contact us form validation #4
  .github/workflows/production.yml
  .gitignore
  src/interfaces/ContactFormInterface.ts
  src/pages/contact/contact-form-section.tsx
Labels: high-priority, feature

#18 Add social media links
  src/pages/blog/hero-section.tsx
  src/pages/event/hero-section.tsx
  src/pages/home/hero-section.tsx
Labels: enhancement, low-priority

#19 Merge Development into Main
  .gitignore
  src/interfaces/ContactFormInterface.ts
  src/pages/blog/hero-section.tsx
  src/pages/contact/contact-form-section.tsx
  src/pages/event/hero-section.tsx
  src/pages/home/hero-section.tsx
Labels: high-priority, feature

#20 Fix/board member alignment issue
  public/assets/boards/2020/dinuwan.jpg
  src/components/nav_bar/index.tsx
  src/pages/board/board-by-year.tsx
  src/styles/board.scss
  src/styles/contactus.scss
Labels: high-priority, fix

#25 This closes #23 contact form validations bug fixed
  package-lock.json
  src/pages/contact/contact-form-section.tsx
  yarn.lock
Labels: bug

#24 Add issue and PR templates
  .github/templates/ISSUE_TEMPLATE.md
  .github/templates/PR_TEMPLATE.md
Labels: documentation, medium-priority
